"""Pydantic models of card data"""
from pydantic import BaseModel

class Card(BaseModel):
    title: str = ...
    url: str = ...
    description: str = ...
    image: str = ...

def parse_cards(data: dict, ) -> list[Card]:
    return None 